llms = {
            "mixtral-8x7b-instruct-v0.1":['together-ai','anyscale','replicate','octoai','mistral-ai','perplexity-ai','fireworks-ai','lepton-ai','deepinfra','aws-bedrock'],
            "llama-2-13b-chat":['anyscale','together-ai','replicate','octoai','fireworks-ai','lepton-ai','deepinfra','aws-bedrock'],
            "llama-2-7b-chat":['anyscale','together-ai','replicate','fireworks-ai','lepton-ai','deepinfra'],
            "gemma-7b-it":['deepinfra','lepton-ai','together-ai','fireworks-ai','anyscale'],
            "codellama-13b-instruct":['together-ai','octoai','fireworks-ai'],
            "yi-34b-chat":['together-ai','deepinfra'],
            "mistral-medium":['mistral-ai'],
            "pplx-70b-chat":['perplexity-ai'],
            "deepseek-coder-33b-instruct":['together-ai'],
            "gpt-4-turbo": ["openai"],
            "mistral-large":['mistral-ai'],
            "claude-3-opus":['anthropic'],
            "llama-2-70b-chat":['anyscale','together-ai','perplexity-ai','replicate','octoai','fireworks-ai','lepton-ai','deepinfra','aws-bedrock'],
            "mistral-7b-instruct-v0.2": ['together-ai','replicate','mistral-ai','perplexity-ai','aws-bedrock','octoai','fireworks-ai'],
            "codellama-34b-instruct": ['anyscale','perplexity-ai','together-ai','octoai','fireworks-ai','deepinfra'],
            "pplx-7b-chat": ['perplexity-ai'],
            "gpt-4": ["openai"],
            "gpt-3.5-turbo": ["openai"],
            "gpt-4o":["openai"],
            "gemma-2b-it": ['together-ai'],
            "mistral-small": ['mistral-ai'],
            "claude-3-haiku": ['anthropic'],
            "anthropic": ['anthropic']
        }